// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AI2eoPgjw',
    appId: '1:869533741414:web:58a7',
    messagingSenderId: '3741414',
    projectId: 'kartac',
    authDomain: 'kartfoseapp.com',
    storageBucket: 'kartforot.com',
    measurementId: 'GPDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIztzCC8',
    appId: '1:869533741414:android:be78358a7',
    messagingSenderId: '8641414',
    projectId: 'kau-23dac',
    storageBucket: 'kartforyou-2spot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_4AqkpUo',
    appId: '1:8695337408358a7',
    messagingSenderId: '869414',
    projectId: 'kaac',
    storageBucket: 'kartfor.com',
    iosClientId: '86953t.com',
    iosBundleId: 'com.lApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAqkpUo',
    appId: '1:858a7',
    messagingSenderId: '81414',
    projectId: 'ac',
    storageBucket: 'karot.com',
    iosClientId: '869533741t.com',
    iosBundleId: 'coests',
  );
}
