// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClAhBj_SXvwq8w3FmGjcebg68b2eoPgjw',
    appId: '1:869533741414:web:52f8965149e9f6f98358a7',
    messagingSenderId: '869533741414',
    projectId: 'kartforyou-23dac',
    authDomain: 'kartforyou-23dac.firebaseapp.com',
    storageBucket: 'kartforyou-23dac.appspot.com',
    measurementId: 'G-3TF0K68PDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtg5sEQHRDY2B4iuHdTnhVPkUwztzCC8',
    appId: '1:869533741414:android:b01445855df6c6e78358a7',
    messagingSenderId: '869533741414',
    projectId: 'kartforyou-23dac',
    storageBucket: 'kartforyou-23dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9hIJmggEtLzmNiM_RVJTdcgy_4AqkpUo',
    appId: '1:869533741414:ios:73e211f014c38db08358a7',
    messagingSenderId: '869533741414',
    projectId: 'kartforyou-23dac',
    storageBucket: 'kartforyou-23dac.appspot.com',
    iosClientId: '869533741414-n18nrgho0cb1j3rkca24dmlssurvqeph.apps.googleusercontent.com',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9hIJmggEtLzmNiM_RVJTdcgy_4AqkpUo',
    appId: '1:869533741414:ios:37337c1ea82f1abf8358a7',
    messagingSenderId: '869533741414',
    projectId: 'kartforyou-23dac',
    storageBucket: 'kartforyou-23dac.appspot.com',
    iosClientId: '869533741414-ocs06mg3g3pf0b84fvqdag2s4imsns5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.callApp.RunnerTests',
  );
}
